# Generated by Django 6.0.4 on 2026-04-27 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='description',
        ),
    ]
