# Generated by Django 6.0.4 on 2026-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='projects', to='project.program'),
        ),
    ]
