# Generated by Django 6.0.4 on 2026-08-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='skill',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
